import { GetStaticProps } from "next"
import Head from 'next/head'
import Header from "../components/Header"
import { Post } from "../typings";
import { fetchPosts } from "../utils/fetchPosts"

type Props = {
	posts: Post[];
}

export default function Home({ posts }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Header posts={posts} name="I'm the header" slogan="hey"  />
		</div>
  ) 
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const posts: Post[] = await fetchPosts();

	return {
		props: {
			posts,
		},

		revalidate: 10,
	}
}